### ISSUE TITLE
Small Issue in a ExamplesAndTests/Examples.ipynb Comment

### ISSUE THREAD

**Issue by zcarter309** [sbaum90/paleoSpec#1]
Hello! In the comment on the 8th line of the 2nd cell in `ExamplesAndTests/Examples.ipynb`, it seems "GSNB" is given as an acronym for the "Diffuse Supernova Neutrino Background", which I assume is not actively intended.
Thanks for reading and for the code!

-Zack

**Comment by sbaum90** [comment]
Hi, 
Thanks for spotting this, it should now be fixed.
/Sebastian
